#!/usr/bin/env bash
# Generate regression ground truth from the current binary.
# Run once after a confirmed-good build; re-run to update after deliberate changes.
# The output file (regression_gt.txt) should be committed alongside this script.
#
# Usage (run from repo root):
#   bash test/gen_regression_gt.sh
#
# Thread count: defaults to hardware_concurrency (--threads 0).
# Override: THREADS=2 bash test/gen_regression_gt.sh

set -uo pipefail

BIN=./build/Release/mtg.exe
GT=test/regression_gt.txt
THREADS=${THREADS:-0}

if [ ! -f "$BIN" ]; then
  echo "ERROR: $BIN not found. Run cmake --build build --config Release first." >&2
  exit 1
fi

run() { "$BIN" "$@" 2>/dev/null | grep "Avg win turn" | sed 's/.*: //' || true; }

COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date +%Y-%m-%d)

echo "Generating ground truth from commit $COMMIT on $DATE ..."
echo "(Using --threads $THREADS; results are thread-invariant)"
echo ""

{
  echo "# Regression ground truth -- commit $COMMIT  date $DATE"
  echo "# Generated by test/gen_regression_gt.sh -- do not edit by hand"
  echo "# Regenerate after deliberate behaviour changes, then commit the new values."
  echo "#"
  echo "# Configs:"
  echo "#   depth 0  = heuristic-only baseline (no search), fast smoke test"
  echo "#   depth 3  = mid-depth search, two seeds to catch seed-specific bugs"
  echo "#   depth 5  = deep search, verify no crash/hang and TT-memoized result is stable"
  echo "#   All runs: --threads \$THREADS (results are thread-invariant)"
  echo "#   d3 budget: 100ms virtual  |  d5 budget: 200ms virtual"
  echo ""

  echo "# slivers_vial  (--lookahead-bottoming enabled for all search runs)"
  printf "slivers_d0_s1001=%s\n" \
    "$(run slivers_vial.txt --profile slivers_vial.profile.json \
        --games 1000 --seed 1001 --threads $THREADS --depth 0)"
  printf "slivers_d3_s1001=%s\n" \
    "$(run slivers_vial.txt --profile slivers_vial.profile.json \
        --games 500 --seed 1001 --threads $THREADS --depth 3 \
        --budget-ms 100 --lookahead-bottoming)"
  printf "slivers_d3_s2002=%s\n" \
    "$(run slivers_vial.txt --profile slivers_vial.profile.json \
        --games 500 --seed 2002 --threads $THREADS --depth 3 \
        --budget-ms 100 --lookahead-bottoming)"
  printf "slivers_d5_s1001=%s\n" \
    "$(run slivers_vial.txt --profile slivers_vial.profile.json \
        --games 500 --seed 1001 --threads $THREADS --depth 5 \
        --budget-ms 200 --lookahead-bottoming)"
  printf "slivers_d5_s2002=%s\n" \
    "$(run slivers_vial.txt --profile slivers_vial.profile.json \
        --games 500 --seed 2002 --threads $THREADS --depth 5 \
        --budget-ms 200 --lookahead-bottoming)"

  echo ""
  echo "# test_deck (burn)"
  printf "burn_d0_s1001=%s\n" \
    "$(run test_deck.txt --games 1000 --seed 1001 --threads $THREADS --depth 0)"
  printf "burn_d3_s1001=%s\n" \
    "$(run test_deck.txt --games 500 --seed 1001 --threads $THREADS \
        --depth 3 --budget-ms 100)"
  printf "burn_d3_s2002=%s\n" \
    "$(run test_deck.txt --games 500 --seed 2002 --threads $THREADS \
        --depth 3 --budget-ms 100)"
  printf "burn_d5_s1001=%s\n" \
    "$(run test_deck.txt --games 500 --seed 1001 --threads $THREADS \
        --depth 5 --budget-ms 200)"
} | tee "$GT"

echo ""
echo "Written to $GT"
