#!/usr/bin/env bash
# A/B for the Karoo TAP-IN-RESPONSE + the USER's bounce order (ONE lever, MTG_BOUNCE_UNTAPPED_FIRST,
# heurarm slot BOUNCE_UNTAPPED_FIRST; USER 2026-10-06), on EVERY regression-tier cell:
#   base   lever OFF (prefer an already-tapped land; an untapped returned land's mana is lost)
#   lever  lever ON  (an untapped free-tapping returned land is tapped for mana in response and the
#                     provider prefers a land that re-enters untapped)
# Adapted from logs/bounce_ab/ab.sh (itself a copy of test/mana_tap_order_ab.sh). Both arms in ONE
# pooled batch, same seeds and game indices -> PAIRED by construction, one load-imbalance tail.
#
# Usage (from the repo root; DECKS = the Karoo decks -- the lever is unreachable in every other deck):
#   DECKS=fungus,hinata,creature_giving,mirrorwing,minotaur,kitty,dragons,melira,selesnya \
#     MTG_BIN=<binary> RUN=<name> bash test/karoo_tap_in_response_ab.sh
#   (2026-10-08: Angels' Azorius Chancery was cut and Bruna is not a suite deck -- DECK_FILE has no
#   `bruna`, so naming it crashes the manifest step. `hinata` / `minotaur` also select their 2HG rows.)
#   CASES=overnight ...                                                   # held-out seeds
#   DRY_RUN=1 ...                                                         # write the manifest only
# Then: python3 test/paired_arms.py logs/karoo/ab/<run>/wins --base base --arm lever --list-moved
# Results (regression tier, then the held-out overnight tier): docs/design/karoo-tap-in-response.md.
# DO NOT edit this file while a run is in flight (bash reads a script by byte offset).
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
. test/lib/harness.sh
source test/regression_cases.sh

BIN=$(harness_bin) || exit 1
TIER=${CASES:-regression}
case "$TIER" in
  smoke)      CASES_REF=("${SMOKE_CASES[@]}") ;;
  regression) CASES_REF=("${REGRESSION_CASES[@]}") ;;
  overnight)  CASES_REF=("${OVERNIGHT_CASES[@]}") ;;
  *) echo "CASES must be smoke|regression|overnight" >&2; exit 2 ;;
esac
RUN=${RUN:-$(date +%Y%m%d_%H%M%S)_$TIER}
OUT=logs/karoo/ab/$RUN
mkdir -p "$OUT/wins"
ONLY=${DECKS:-}

python3 - "$OUT/manifest.json" "$ONLY" "${CASES_REF[@]}" <<'PY'
import json, sys, os, re
out, only = sys.argv[1], sys.argv[2]
cases = sys.argv[3:]
only = set(only.split(",")) if only else None
# DECK_FILE / DECK_PROF are bash assoc arrays; re-read them from the cases file.
src = open("test/regression_cases.sh").read()
def amap(name):
    m = re.search(r"declare -A %s=\((.*?)\n\)" % name, src, re.S)
    d = {}
    for k, v in re.findall(r'^\s*\[([a-z0-9_]+)\]=(.+)$', m.group(1), re.M):
        d[k] = v.strip().strip('"')
    return d
FILE, PROF = amap("DECK_FILE"), amap("DECK_PROF")
ARMS = {"base": {"MTG_BOUNCE_UNTAPPED_FIRST": False}, "lever": {"MTG_BOUNCE_UNTAPPED_FIRST": True}}
jobs = []
for spec in cases:
    deck, depth, seed, games, budget = spec.split()
    depth, seed, games, budget = int(depth), int(seed), int(games), int(budget)
    base = deck[:-3] if deck.endswith("2hg") else deck
    if only and deck not in only and base not in only: continue
    extra = {"starting_life": 30, "opponent_heads": 2} if deck.endswith("2hg") else {}
    bud = budget if depth > 0 else 0
    weight = (depth * 1000 + bud) if (base == "hinata" and depth > 0) else 0
    for arm, flags in ARMS.items():
        # paired_arms.py splits the .wins name on "__": everything before is the row key.
        j = {"name": f"{deck}_d{depth}_s{seed}__{arm}", "deck": FILE[base], "profile": PROF[base],
             **extra, "games": games, "seed": seed, "budget_ms": bud, "weight": weight, "flags": flags}
        if depth != 5:   # d5 cells drop the depth key so value_play owns it (regression.sh's rule)
            j["depth"] = depth; j["ignore_play_profile"] = True
        jobs.append(j)
json.dump({"jobs": jobs}, open(out, "w"), indent=1)
print(f"{len(jobs)} jobs, {sum(j['games'] for j in jobs)} games ({len(ARMS)} arms)")
PY

[[ -n "${DRY_RUN:-}" ]] && { echo "DRY_RUN: manifest at $OUT/manifest.json"; exit 0; }
echo "--- running $TIER cells x $(python3 -c "import json;print(len({j['name'].split('__')[1] for j in json.load(open('$OUT/manifest.json'))['jobs']}))") arms on $BIN -> $OUT ---"
MTG_DUMP_UNITS=1 "$BIN" --batch "$OUT/manifest.json" --threads "${THREADS:-0}" --game-log-dir "$OUT/wins" \
    >"$OUT/batch.out" 2>"$OUT/batch.err"
rc=$?
echo "batch rc=$rc"
grep -E "heartbeat|SLOW-GAME" "$OUT/batch.err" | tail -8
ARMLIST=$(python3 -c "import json,sys; m=json.load(open('$OUT/manifest.json'))['jobs']; print(' '.join(sorted({j['name'].split('__')[1] for j in m}-{'base'})))")
for arm in $ARMLIST; do
  echo; echo "=== $arm vs base ==="
  python3 test/paired_arms.py "$OUT/wins" --base base --arm "$arm"
done | tee "$OUT/paired.txt"
