#!/usr/bin/env bash
# A/B for the two mana-source tap-order levers (USER 2026-10-05), on EVERY regression-tier cell:
#
#   MTG_NEEDS_TAP_ORDER        needs-based source choice among the plain-land tiers (hand, board
#                              activations, then one expected reveal from the library) -- see
#                              ComputeNeedsDemandSupply in src/ai/ManaPayment.cpp.
#   MTG_ATTACK_BODY_TAP_ORDER  on a pre-combat main with an eligible attacker, equal-rank mana
#                              creatures tap lowest-attack-power first -- see
#                              DecisionProvider::ManaSourceHoldValue.
#
# EVERY ARM IN ONE POOLED BATCH, every arm on the same seeds and game indices, so the comparison is
# PAIRED by construction and the box pays ONE load-imbalance tail (CLAUDE.md: never a loop of
# per-arm batches; paired heuristics are tested JOINTLY, so the joint arm is not optional). Cells
# are the regression tier's own (test/regression_cases.sh): the suite IS the A/B, pooled across
# arms. Held-out confirmation uses the OVERNIGHT tier's seeds (CASES=overnight).
#
# ARMSET selects the arm set (see ARMSETS below):
#   levers   (default) base / needs / attack / both          -- the two tap-order levers
#   rollback           base / rollback / all3                -- the payment rollback alone and on top
#   all                base / needs / attack / both / rollback / all3   (930 jobs on the regression tier)
#
# Usage:
#   bash test/mana_tap_order_ab.sh                 # regression-tier cells, the `levers` arms
#   ARMSET=all RUN=<name> MTG_BIN=<binary> bash test/mana_tap_order_ab.sh
#   CASES=overnight bash test/mana_tap_order_ab.sh # held-out seeds
#   DECKS=snow,mirrorwing bash test/mana_tap_order_ab.sh   # restrict to decks (comma list of case keys)
#   DRY_RUN=1 ...                                  # write the manifest only
# Then: python3 test/paired_arms.py logs/mana_tap_ab/<run>/wins --base base --arm needs [--list-moved]
# (the script runs this for every arm into <run>/paired.txt). DO NOT edit this file while a run is
# in flight: bash reads a script by byte offset, and an edit shifted round 2's post-batch step into
# the middle of the manifest heredoc.
set -uo pipefail
cd "$(dirname "$0")/.."
. test/lib/harness.sh
source test/regression_cases.sh

BIN=$(harness_bin) || exit 1
TIER=${CASES:-regression}
case "$TIER" in
  smoke)      CASES_REF=("${SMOKE_CASES[@]}") ;;
  regression) CASES_REF=("${REGRESSION_CASES[@]}") ;;
  overnight)  CASES_REF=("${OVERNIGHT_CASES[@]}") ;;
  *) echo "CASES must be smoke|regression|overnight" >&2; exit 2 ;;
esac
RUN=${RUN:-$(date +%Y%m%d_%H%M%S)_$TIER}
OUT=logs/mana_tap_ab/$RUN
mkdir -p "$OUT/wins"
ONLY=${DECKS:-}

python3 - "$OUT/manifest.json" "$ONLY" "${CASES_REF[@]}" <<'PY'
import json, sys, os, re
out, only = sys.argv[1], sys.argv[2]
cases = sys.argv[3:]
only = set(only.split(",")) if only else None
# DECK_FILE / DECK_PROF are bash assoc arrays; re-read them from the cases file.
src = open("test/regression_cases.sh").read()
def amap(name):
    m = re.search(r"declare -A %s=\((.*?)\n\)" % name, src, re.S)
    d = {}
    for k, v in re.findall(r'^\s*\[([a-z0-9_]+)\]=(.+)$', m.group(1), re.M):
        d[k] = v.strip().strip('"')
    return d
FILE, PROF = amap("DECK_FILE"), amap("DECK_PROF")
ARMSETS = {
    # the two tap-order levers, singly and jointly
    "levers": {
        "base":   {"MTG_NEEDS_TAP_ORDER": False, "MTG_ATTACK_BODY_TAP_ORDER": False},
        "needs":  {"MTG_NEEDS_TAP_ORDER": True,  "MTG_ATTACK_BODY_TAP_ORDER": False},
        "attack": {"MTG_NEEDS_TAP_ORDER": False, "MTG_ATTACK_BODY_TAP_ORDER": True},
        "both":   {"MTG_NEEDS_TAP_ORDER": True,  "MTG_ATTACK_BODY_TAP_ORDER": True},
    },
    # the mana-payment ROLLBACK (src/ai/PayRollback.h), alone and on top of both levers
    "rollback": {
        "base":     {"MTG_NEEDS_TAP_ORDER": False, "MTG_ATTACK_BODY_TAP_ORDER": False, "MTG_PAY_ROLLBACK": False},
        "rollback": {"MTG_NEEDS_TAP_ORDER": False, "MTG_ATTACK_BODY_TAP_ORDER": False, "MTG_PAY_ROLLBACK": True},
        "all3":     {"MTG_NEEDS_TAP_ORDER": True,  "MTG_ATTACK_BODY_TAP_ORDER": True,  "MTG_PAY_ROLLBACK": True},
    },
    # every arm in ONE pool: the two levers singly and jointly, the rollback alone, all three
    "all": {
        "base":     {"MTG_NEEDS_TAP_ORDER": False, "MTG_ATTACK_BODY_TAP_ORDER": False, "MTG_PAY_ROLLBACK": False},
        "needs":    {"MTG_NEEDS_TAP_ORDER": True,  "MTG_ATTACK_BODY_TAP_ORDER": False, "MTG_PAY_ROLLBACK": False},
        "attack":   {"MTG_NEEDS_TAP_ORDER": False, "MTG_ATTACK_BODY_TAP_ORDER": True,  "MTG_PAY_ROLLBACK": False},
        "both":     {"MTG_NEEDS_TAP_ORDER": True,  "MTG_ATTACK_BODY_TAP_ORDER": True,  "MTG_PAY_ROLLBACK": False},
        "rollback": {"MTG_NEEDS_TAP_ORDER": False, "MTG_ATTACK_BODY_TAP_ORDER": False, "MTG_PAY_ROLLBACK": True},
        "all3":     {"MTG_NEEDS_TAP_ORDER": True,  "MTG_ATTACK_BODY_TAP_ORDER": True,  "MTG_PAY_ROLLBACK": True},
    },
}
ARMS = ARMSETS[os.environ.get("ARMSET", "levers")]
jobs = []
for spec in cases:
    deck, depth, seed, games, budget = spec.split()
    depth, seed, games, budget = int(depth), int(seed), int(games), int(budget)
    base = deck[:-3] if deck.endswith("2hg") else deck
    if only and deck not in only and base not in only: continue
    extra = {"starting_life": 30, "opponent_heads": 2} if deck.endswith("2hg") else {}
    bud = budget if depth > 0 else 0
    weight = (depth * 1000 + bud) if (base == "hinata" and depth > 0) else 0
    for arm, flags in ARMS.items():
        # paired_arms.py splits the .wins name on "__": everything before is the row key.
        j = {"name": f"{deck}_d{depth}_s{seed}__{arm}", "deck": FILE[base], "profile": PROF[base],
             **extra, "games": games, "seed": seed, "budget_ms": bud, "weight": weight, "flags": flags}
        if depth != 5:   # d5 cells drop the depth key so value_play owns it (regression.sh's rule)
            j["depth"] = depth; j["ignore_play_profile"] = True
        jobs.append(j)
json.dump({"jobs": jobs}, open(out, "w"), indent=1)
print(f"{len(jobs)} jobs, {sum(j['games'] for j in jobs)} games ({len(ARMS)} arms)")
PY

[[ -n "${DRY_RUN:-}" ]] && { echo "DRY_RUN: manifest at $OUT/manifest.json"; exit 0; }
echo "--- running $TIER cells x $(python3 -c "import json;print(len({j['name'].split('__')[1] for j in json.load(open('$OUT/manifest.json'))['jobs']}))") arms on $BIN -> $OUT ---"
MTG_DUMP_UNITS=1 "$BIN" --batch "$OUT/manifest.json" --threads "${THREADS:-0}" --game-log-dir "$OUT/wins" \
    >"$OUT/batch.out" 2>"$OUT/batch.err"
rc=$?
echo "batch rc=$rc"
grep -E "heartbeat|SLOW-GAME" "$OUT/batch.err" | tail -8
ARMLIST=$(python3 -c "import json,sys; m=json.load(open('$OUT/manifest.json'))['jobs']; print(' '.join(sorted({j['name'].split('__')[1] for j in m}-{'base'})))")
for arm in $ARMLIST; do
  echo; echo "=== $arm vs base ==="
  python3 test/paired_arms.py "$OUT/wins" --base base --arm "$arm"
done | tee "$OUT/paired.txt"
