#!/usr/bin/env bash
# A/B for MTG_RESTRICTED_MANA_RANK (heurarm slot RESTRICTED_MANA_RANK): a colored_creature_only source
# whose restricted colours this deck's creature spells can use number at most ONE ranks as a {C}
# source plus one creature-only colour (below the mono tier) instead of a rainbow held last of the
# lands. See ManaSourceRankBase / NarrowRestrictedMask (src/ai/DecisionProviders.cpp).
#   base   lever OFF (the historical ladder)
#   lever  lever ON
# ALL THREE TIERS' rows of the named decks in ONE pooled batch (smoke + regression = train,
# overnight = held-out), both arms on the same seeds and game indices -> PAIRED by construction and
# one load-imbalance tail (CLAUDE.md: never a loop of per-tier or per-arm batches).
#
# Usage (from the repo root; DECKS = case keys, a deck key also selects its 2HG rows):
#   DECKS=dragons,goblins MTG_BIN=<binary> RUN=<name> bash test/restricted_mana_rank_ab.sh
#   DRY_RUN=1 ...                       # write the manifest only
# The report (per deck x train/held-out, net turns, every slower game) is written to <run>/report.txt;
# REPORT_ONLY=1 RUN=<run> re-prints it without running.
# DO NOT edit this file while a run is in flight (bash reads a script by byte offset).
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
. test/lib/harness.sh
source test/regression_cases.sh

BIN=$(harness_bin) || exit 1
RUN=${RUN:-$(date +%Y%m%d_%H%M%S)}
OUT=logs/restricted_rank/$RUN
mkdir -p "$OUT/wins"
ONLY=${DECKS:-}

python3 - "$OUT/manifest.json" "$ONLY" \
    "smoke" "${SMOKE_CASES[@]}" "regression" "${REGRESSION_CASES[@]}" "overnight" "${OVERNIGHT_CASES[@]}" <<'PY'
import json, sys, re
out, only = sys.argv[1], sys.argv[2]
only = set(only.split(",")) if only else None
src = open("test/regression_cases.sh").read()
def amap(name):
    m = re.search(r"declare -A %s=\((.*?)\n\)" % name, src, re.S)
    d = {}
    for k, v in re.findall(r'^\s*\[([a-z0-9_]+)\]=(.+)$', m.group(1), re.M):
        d[k] = v.strip().strip('"')
    return d
FILE, PROF = amap("DECK_FILE"), amap("DECK_PROF")
ARMS = {"base": {"MTG_RESTRICTED_MANA_RANK": False},
        "lever": {"MTG_RESTRICTED_MANA_RANK": True}}
jobs, tier = [], None
for spec in sys.argv[3:]:
    if spec in ("smoke", "regression", "overnight"):
        tier = spec
        continue
    deck, depth, seed, games, budget = spec.split()
    depth, seed, games, budget = int(depth), int(seed), int(games), int(budget)
    base = deck[:-3] if deck.endswith("2hg") else deck
    if only and deck not in only and base not in only: continue
    extra = {"starting_life": 30, "opponent_heads": 2} if deck.endswith("2hg") else {}
    bud = budget if depth > 0 else 0
    for arm, flags in ARMS.items():
        # paired_arms.py splits the .wins name on "__": everything before is the row key.
        j = {"name": f"{tier}.{deck}_d{depth}_s{seed}__{arm}", "deck": FILE[base], "profile": PROF[base],
             **extra, "games": games, "seed": seed, "budget_ms": bud, "flags": flags}
        if depth != 5:   # d5 cells drop the depth key so value_play owns it (regression.sh's rule)
            j["depth"] = depth; j["ignore_play_profile"] = True
        jobs.append(j)
json.dump({"jobs": jobs}, open(out, "w"), indent=1)
print(f"{len(jobs)} jobs, {sum(j['games'] for j in jobs)} games ({len(ARMS)} arms)")
PY

[[ -n "${DRY_RUN:-}" ]] && { echo "DRY_RUN: manifest at $OUT/manifest.json"; exit 0; }
if [[ -z "${REPORT_ONLY:-}" ]]; then
  echo "--- running on $BIN -> $OUT ---"
  MTG_DUMP_UNITS=1 "$BIN" --batch "$OUT/manifest.json" --threads "${THREADS:-0}" --game-log-dir "$OUT/wins" \
      >"$OUT/batch.out" 2>"$OUT/batch.err"
  rc=$?
  echo "batch rc=$rc"
  grep -E "heartbeat|SLOW-GAME" "$OUT/batch.err" | tail -8
fi
# Per deck x (train = smoke + regression, held-out = overnight): games, faster / slower, NET turns
# (sum of per-game deltas, an unwon game scored max_turns+1 = 9), units ratio; then every slower game.
python3 - "$OUT/wins" <<'PY' | tee "$OUT/report.txt"
import os, sys, collections
d = sys.argv[1]
def wins(p):
    out = {}
    for line in open(p):
        f = line.split()
        if len(f) >= 2: out[int(f[0])] = 9 if int(f[1]) < 0 else int(f[1])
    return out
def units(p):
    if not os.path.exists(p): return 0
    return sum(int(l.split()[1]) for l in open(p) if len(l.split()) >= 2)
agg = collections.defaultdict(lambda: [0, 0, 0, 0, 0, 0])   # games faster slower net ub ua
slow = []
for fn in sorted(os.listdir(d)):
    if not fn.endswith("__base.wins"): continue
    row = fn[:-len("__base.wins")]
    pa = os.path.join(d, row + "__lever.wins")
    if not os.path.exists(pa): continue
    tier, cell = row.split(".", 1)
    deck = cell.split("_d")[0]
    depth = cell.split("_d")[1].split("_")[0]
    grp = "held-out" if tier == "overnight" else "train"
    wb, wa = wins(os.path.join(d, fn)), wins(pa)
    a = agg[(deck, grp)]
    for g in sorted(set(wb) & set(wa)):
        a[0] += 1
        if wa[g] < wb[g]: a[1] += 1
        if wa[g] > wb[g]:
            a[2] += 1; slow.append((grp, row, depth, g, wb[g], wa[g]))
        a[3] += wa[g] - wb[g]
    a[4] += units(os.path.join(d, row + "__base.units")); a[5] += units(os.path.join(d, row + "__lever.units"))
print(f"{'deck':<14}{'set':<10}{'games':>8}{'faster':>8}{'slower':>8}{'net':>7}{'units':>9}")
for (deck, grp), a in sorted(agg.items()):
    print(f"{deck:<14}{grp:<10}{a[0]:>8}{a[1]:>8}{a[2]:>8}{a[3]:>+7}{(a[5]/a[4] if a[4] else float('nan')):>9.4f}")
print(f"\nSLOWER GAMES ({len(slow)})   set row depth gi base -> lever")
for s in slow: print("  %-9s %-34s d%-2s gi=%-5d %d -> %d" % s)
PY
