#!/usr/bin/env python3
"""Resolve a rebase conflict in test/regression_gt.txt mechanically.

The GT file is a generated artifact: every smoke/regression value in it is
re-measured by 'regression.sh --accept' once the rebase lands, so the merge
only has to keep the file *well-formed* -- not correct.

Two rules, and they differ because the two halves of the file have different
lifetimes:

  header comments  -> keep OURS (the rebase base). The base carries the
                      accepted-with-regressions notes, which are a record of a
                      user decision and must never be dropped by a merge.
  data lines       -> keep THEIRS (the commit being replayed), i.e. the branch
                      being rebased wins, because its later commits are still
                      to come and would re-set the value anyway.

Overnight values are NOT regenerated by the post-rebase accept; those are
restored separately from the integration target.
"""
import re
import sys

path = sys.argv[1] if len(sys.argv) > 1 else "test/regression_gt.txt"
lines = open(path).read().split("\n")

out, ours, theirs, side = [], [], [], None
for ln in lines:
    if ln.startswith("<<<<<<<"):
        side, ours, theirs = "ours", [], []
    elif ln.startswith("=======") and side == "ours":
        side = "theirs"
    elif ln.startswith(">>>>>>>") and side == "theirs":
        for block, keep_comments in ((ours, True), (theirs, False)):
            for c in block:
                is_comment = c.startswith("#")
                if is_comment == keep_comments:
                    out.append(c)
        side = None
    elif side == "ours":
        ours.append(ln)
    elif side == "theirs":
        theirs.append(ln)
    else:
        out.append(ln)

if side is not None:
    sys.exit(f"unterminated conflict marker in {path}")

# The header's "commit <sha>" line is stamped by --accept; leave one, not two.
seen_commit = False
final = []
for ln in out:
    if re.match(r"^# Regression ground truth -- commit ", ln):
        if seen_commit:
            continue
        seen_commit = True
    final.append(ln)

open(path, "w").write("\n".join(final))
print(f"resolved {path}: {len(final)} lines")
