# Build-time engine fingerprint (see docs/design/execution-trace-carry.md, Phase B).
#
# Hashes every C++ SOURCE file under src/ (the compiled ENGINE) but NOT the card DATA
# (src/cards/data/*.json is not .h/.cpp so it is naturally excluded). The result is a
# deterministic, cross-machine-stable digest of the engine code, written as a macro into
# a generated header. The mulligan re-run carry compares this "new build" fingerprint to
# the one stamped in a prior sidecar: card-level trace reuse is trusted ONLY when the
# engine fingerprint is unchanged (a shared-code change can move any cell), otherwise it
# refuses and falls back to statistical / full re-sampling.
#
# Distinct from MTG_COMMIT (which bumps for ANY commit, incl. docs and card-data edits):
# this changes iff the compiled engine changed, so "card data changed" stays separable
# from "engine changed".
#
# Invoked via `cmake -P` as a custom command on every build, so it tracks the actual
# source on disk (not just configure-time state). Writes OUT_FILE only when the content
# changes, to avoid a spurious recompile every build.
#
# Args (passed with -D): SRC_DIR (the src/ root), OUT_FILE (header to generate).

file(GLOB_RECURSE _eng_srcs
     LIST_DIRECTORIES false
     "${SRC_DIR}/*.h" "${SRC_DIR}/*.hpp" "${SRC_DIR}/*.cpp" "${SRC_DIR}/*.inl")
list(SORT _eng_srcs)

set(_acc "")
foreach(_f ${_eng_srcs})
    file(SHA256 "${_f}" _h)
    file(RELATIVE_PATH _rel "${SRC_DIR}" "${_f}")
    string(APPEND _acc "${_rel}:${_h}\n")
endforeach()
string(SHA256 _fp "${_acc}")

set(_content "#pragma once\n// GENERATED by cmake/EngineFingerprint.cmake -- do not edit.\n#define MTG_ENGINE_FP \"${_fp}\"\n")

set(_old "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT_FILE}" "${_content}")
endif()
