# Build-time MTG_* flag registry (backlog A3 step 4 / D1).
#
# Scans every C++ source under src/ for string literals of the form "MTG_..." and emits them,
# sorted and deduplicated, as the array in a generated header. This is the set of env flags the
# compiled binaries can actually read; the startup validator (src/core/FlagRegistry.cpp) compares
# the process environment against it so a typo'd or deleted MTG_* var WARNS instead of silently
# no-oping (a silent no-op corrupts an A/B arm -- the arm reads as "flag on" when nothing changed).
#
# Generated from source rather than hand-maintained so it cannot drift: a new EnvOn("MTG_X") site
# is in the registry on the next build, and a deleted flag drops out the same way. Over-inclusion
# (an "MTG_..." literal that is not an env read, e.g. in a log message) is harmless -- it only
# whitelists a name the validator would otherwise flag.
#
# Also whitelists, beyond the source scan:
#   - KEY names from src/ai/data/heuristic_defaults.env (applied via setenv at startup, so they
#     appear in the environment even when no source literal names them)
#   - MTG_BIN: the test harness's binary-path pass-through (exported to child processes that
#     spawn mtg, so it is legitimately present in the environment without being read by C++)
#
# Invoked via `cmake -P` as a custom target on every build (same pattern as
# EngineFingerprint.cmake); writes OUT_FILE only when the content changes so an unchanged
# registry never triggers a recompile.
#
# Args (passed with -D): SRC_DIR (the src/ root), OUT_FILE (header to generate).

file(GLOB_RECURSE _srcs
     LIST_DIRECTORIES false
     "${SRC_DIR}/*.h" "${SRC_DIR}/*.hpp" "${SRC_DIR}/*.cpp" "${SRC_DIR}/*.inl")
list(SORT _srcs)

set(_names "MTG_BIN")
foreach(_f ${_srcs})
    file(READ "${_f}" _txt)
    string(REGEX MATCHALL "\"MTG_[A-Z0-9_]+\"" _ms "${_txt}")
    foreach(_m ${_ms})
        string(REPLACE "\"" "" _m "${_m}")
        list(APPEND _names "${_m}")
    endforeach()
endforeach()

if(EXISTS "${SRC_DIR}/ai/data/heuristic_defaults.env")
    file(STRINGS "${SRC_DIR}/ai/data/heuristic_defaults.env" _lines)
    foreach(_l ${_lines})
        if(_l MATCHES "^(MTG_[A-Z0-9_]+)=")
            list(APPEND _names "${CMAKE_MATCH_1}")
        endif()
    endforeach()
endif()

list(REMOVE_DUPLICATES _names)
list(SORT _names)

set(_content "#pragma once\n// GENERATED by cmake/FlagRegistry.cmake -- do not edit. Sorted; binary-searchable.\ninline const char* const kKnownMtgFlags[] = {\n")
foreach(_n ${_names})
    string(APPEND _content "    \"${_n}\",\n")
endforeach()
string(APPEND _content "};\n")

set(_old "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT_FILE}" "${_content}")
endif()
